DROP DATABASE IF EXISTS `core`;
CREATE DATABASE `core` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
DROP DATABASE IF EXISTS `fivem`;
CREATE DATABASE `fivem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;