version: "3.1"
services:
  mysql:
    container_name: mysql
    image: registry.cn-shanghai.aliyuncs.com/csvw/mysql:8.4.2
    restart: always
    ports:
      - 13306:3306
    volumes:
      # - ./mysql/conf:/etc/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
    secrets:
      - mysql_secret
secrets:
  mysql_secret:
    file: ./secret/mysql
