services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
        #- ./jenkins:/usr/share/jenkins/
  ssh-agent:
    image: jenkins/ssh-agent