services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
        #- ./jenkins:/usr/share/jenkins/
  ssh-agent:
    image: jenkins/ssh-agent