version: "3.1"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
    secrets:
      - mysql_secret
secrets:
  mysql_secret:
    file: ./mysql/secret/mysql