version: "3.1"
services:
  build-runner:
    container_name: build-runner
    image: gitlab/gitlab-runner:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/gitlab-runner
      - /run/docker.sock:/var/run/docker.sock
